"""World state: plot direction, intent forecast, plot threads, summary."""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

from ..config import DEFAULT_PROMPT_HISTORY_CLAMP_CHARS
from .ids import new_id


class PacePreference(StrEnum):
    faster = "faster"
    same = "same"
    slower = "slower"


class TonePreference(StrEnum):
    focus = "focus"
    chaos = "chaos"
    unspecified = "unspecified"


class DirectionSignal(StrEnum):
    stay_focused = "stay_focused"
    reintroduce_thread = "reintroduce_thread"
    none = "none"


class EvidenceQuote(BaseModel):
    model_config = ConfigDict(extra="forbid")

    text: str
    source_node_id: str | None = None


class PlayerIntentForecast(BaseModel):
    model_config = ConfigDict(extra="forbid")

    pace_preference: PacePreference = PacePreference.same
    tone_preference: TonePreference = TonePreference.unspecified
    direction_signal: DirectionSignal = DirectionSignal.none
    weighted_evidence: list[EvidenceQuote] = Field(default_factory=list)


class PlotThread(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=new_id)
    title: str
    summary: str
    last_referenced_node_id: str | None = None


class PlotStage(BaseModel):
    """One stage of the broad plot arc set up at world init.

    The full ``plot_outline`` (a list of these) is the LLM's
    long-form plan for the game — set up at world_init, only
    revised by the summarizer when the actual story has drifted
    enough that the plan no longer fits. The storyteller never
    sees the full outline; the summarizer pulls the currently-
    active stage and feeds that one slice to text_gen.

    Why this matters: passing the full multi-stage outline to the
    storyteller every turn floods it with future-stage spoilers,
    causing it to dump beats from late stages into the current
    scene. The slice contract keeps the storyteller focused on
    "what should happen RIGHT NOW" while the summarizer holds the
    map of where we are in the longer arc.
    """

    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=new_id)
    title: str  # short label, e.g. "The keeper goes missing"
    goal: str  # what this stage must accomplish, 1 sentence
    summary: str  # 1–3 sentences of beats / shape


class WorldState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    game_name: str
    setting: str
    genre: str
    visual_style: str
    # Legacy single-string plot direction. Retained on the model
    # so old saves load without migration; new games populate the
    # structured ``plot_outline`` instead and leave this empty.
    # The storyteller no longer reads this field directly.
    overall_plot_direction: str = ""
    # Structured multi-stage plan. Established at world_init by the
    # opening-scene LLM; revised only by the summarizer when drift
    # is detected. The storyteller is shown ONLY the stage pointed
    # at by ``current_stage_id`` (via text_gen's slice helper).
    plot_outline: list[PlotStage] = Field(default_factory=list)
    current_stage_id: str | None = None
    player_intent: PlayerIntentForecast = Field(default_factory=PlayerIntentForecast)
    active_plot_threads: list[PlotThread] = Field(default_factory=list)
    dropped_plot_threads: list[PlotThread] = Field(default_factory=list)
    summarizer_assessment: str = ""
    prompt_history_clamp_chars: int = DEFAULT_PROMPT_HISTORY_CLAMP_CHARS
    # Background music — a single looping instrumental track that
    # plays under the whole game. Generated by the ACE-Step
    # backend when ``MusicSettings.enabled`` is True; the
    # storyteller can swap it via beat-emitted ``music_change``
    # entries. Empty / None when music gen is disabled or the
    # initial render hasn't completed yet. ``music_path`` is
    # absolute on disk; ``music_prompt`` is the text prompt the
    # ACE-Step pipeline rendered against (kept for diagnostics
    # and so a rerender uses the same input); ``music_prompt_hash``
    # gates the asset-pipeline freshness check the same way
    # ``Environment.audio_prompt_hash`` does.
    music_path: str | None = None
    music_prompt: str = ""
    music_prompt_hash: str = ""

    def current_stage(self) -> PlotStage | None:
        """Return the currently-active stage, or None if the outline
        is empty / the pointer is unset (e.g. legacy save)."""
        if not self.current_stage_id:
            return None
        for stage in self.plot_outline:
            if stage.id == self.current_stage_id:
                return stage
        return None
